apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vote-route
  labels:
    app.kubernetes.io/name: vote-app
spec:
  hosts:
  - "vote.devopshub.cn"
  gateways:
  - vote-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: vote
        subset: v2
        port:
          number: 5001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: result-route
  labels:
    app.kubernetes.io/name: vote-app
spec:
  hosts:
  - "result.devopshub.cn"
  gateways:
  - result-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /stylesheets
    - uri:
        prefix: /socket.io
    - uri:
        regex: '^.*\.(ico|png|jpg|js)$'
    route:
    - destination:
        host: result
        subset: v2
        port:
          number: 5002


