apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote-ui
  namespace: default
  labels:
    service: vote-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: vote-ui-v2
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60